### ISSUE TITLE
currently app deployed to URL with hyphen http://av-certificates.herokuapp.com/

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/certificates#13]
This causes a line break in the certificate and the certificate pdf to hyperlink to the wrong place:

![line broken hyperlink](https://www.dropbox.com/s/9x0agnwus4xflee/Screenshot%202016-01-27%2012.34.49.png?dl=1)

**Comment by tansaku** [comment]
create subdomain?

**Comment by tochman** [comment]
Why not split this in to 2 lines? I would suggest this change:
```ruby
# av_certs.rb:48
pdf.move_down 420
pdf.text "To verify the authenticity of this certificate, please visit", size: 9, color: '575756', align: :center
pdf.text "http://agileventures.org/verify/#{@cert.identifier}", size: 9, color: '575756', align: :center
```

**Comment by tochman** [comment]
Or use a url shortening service. (I do that in the workshop tutorial I'm running for Craft Academy)

**Comment by tansaku** [comment]
I've got the subdomain working now, so locally when I generate a cert it looks like this:

[not broken](https://www.dropbox.com/s/uzqiq5i83ledlni/Screenshot%202016-01-27%2017.03.14.png?dl=1)

but when I do it on heroku it breaks (although now in a good place) but gets obscured:

[breaks](https://www.dropbox.com/s/o8gntsc9a7758ui/Screenshot%202016-01-27%2017.03.48.png?dl=0)

url shortening sure but I guess I'd have to pull in a gem to do that automatically for the cert ...

**Comment by tansaku** [comment]
@tochman I've broken the thing over two lines - looks like this now:  

![looks okay](https://www.dropbox.com/s/abl0o5mj065f2t9/Screenshot%202016-01-28%2008.10.35.png?dl=1)

**Comment by tansaku** [comment]
and unlike our previous certs the link actually links to a working end point ... this is on the heroku server, but not yet in git due to the csv file concerns - hopefully I can tidy up with some pull requests when I've done some more of the overdue certs ...
